"""Add new column to database

Revision ID: 48170418e88d
Revises: 5dd1bd3eaed1
Create Date: 2024-07-23 04:21:45.007230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48170418e88d'
down_revision = '5dd1bd3eaed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.alter_column('Age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.alter_column('Age',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
