"""Add new column to database

Revision ID: 5dd1bd3eaed1
Revises: 9e2bd0affc27
Create Date: 2024-07-23 04:02:01.553543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd1bd3eaed1'
down_revision = '9e2bd0affc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LastName', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('OtherNames', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('PhoneNumber', sa.String(length=16), nullable=False))
        batch_op.alter_column('Gender',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('Gender',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
        batch_op.drop_column('PhoneNumber')
        batch_op.drop_column('OtherNames')
        batch_op.drop_column('LastName')

    # ### end Alembic commands ###
