"""Add new column to database

Revision ID: 5ee93bde2498
Revises: 48170418e88d
Create Date: 2024-07-23 04:52:37.747168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee93bde2498'
down_revision = '48170418e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EmailAddress', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.drop_column('EmailAddress')

    # ### end Alembic commands ###
