"""Add new column to database

Revision ID: 602ed6137944
Revises: cd450bfb5530
Create Date: 2024-07-22 18:52:56.680657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602ed6137944'
down_revision = 'cd450bfb5530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.alter_column('Gender',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.alter_column('Gender',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
