"""Add new column to database

Revision ID: 9e2bd0affc27
Revises: 602ed6137944
Create Date: 2024-07-23 03:28:37.512618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2bd0affc27'
down_revision = '602ed6137944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=16), nullable=False))
        batch_op.alter_column('Status',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_info', schema=None) as batch_op:
        batch_op.alter_column('Status',
               existing_type=sa.String(length=10),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
