"""Initial migration.

Revision ID: cd450bfb5530
Revises: 
Create Date: 2024-07-22 16:53:38.537965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd450bfb5530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.String(length=100), nullable=False),
    sa.Column('Status', sa.Numeric(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_info')
    # ### end Alembic commands ###
